# Generated by Django 3.2.8 on 2021-10-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_awards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='information',
            new_name='info',
        ),
    ]
